### ISSUE TITLE
Cop idea: [FactoryGirl] replaces n.times { create } with create_list

### ISSUE THREAD

**Issue by Darhazer** [rubocop-rspec/rubocop-rspec#411]
Now that we have the first candidate for a FactoryGirl specific cop, here's another one
I often see people use `10.times { create :user }`, while it can be done with `create_list :user, 10`
Note: in the case the block parameter of time is used, create_list is no longer valid approach, like in
`10.times { |n| create :user, registered_at: n.days.ago }`

**Comment by backus** [comment]
Good idea
