### ISSUE TITLE
Capybara/FeatureMethods: False positive in FactoryGirls factory.

### ISSUE THREAD

**Issue by 6temes** [rubocop-rspec/rubocop-rspec#474]
This file creates a false positive when running Rubocop. 
The autocorrect also will change the word `feature` for `describe`.

```ruby
# spec/factories/things.rb

FactoryGirl.define do
  factory :thing do
    name 'my_name'
    feature 'my_feature'
  end
end
```

Rubocop version: 0.5.0
Rubocop-rspec version: 1.17.1

**Comment by Darhazer** [comment]
This is already fixed in `master`, see #469
I will prepare a release soon

**Comment by 6temes** [comment]
Thanks!

**Comment by dkniffin** [comment]
@Darhazer @bquorning I don't think this is resolved. I'm running version 1.24.0 and I'm still seeing the issue.

Here's my factory:

```rb
FactoryGirl.define do
  factory :company do
    name { Faker::Company.unique.name }

    # ...

    trait :with_background do
      background { Faker::Lorem.sentence }
    end
  end
end
```

running rubocop, I get:

```
spec/factories/companies.rb:19:7: C: Capybara/FeatureMethods: Use before instead of background.
      background { Faker::Lorem.sentence }
      ^^^^^^^^^^
```
