### ISSUE TITLE
Cop idea: don't allow be without arguments

### ISSUE THREAD

**Issue by Darhazer** [rubocop-rspec/rubocop-rspec#531]
I came across this 3 years old discussion about using `be` without arguments: 
https://github.com/rspec/rspec-expectations/issues/761

It will be nice to have a cop to detect such usage and it will actually help with the deprecation ;)

**Comment by bquorning** [comment]
I’ve sometimes used `expect(foo).to be` to mean `expect(foo).to_not be_nil`. But while the first form is tongue-in-cheek, the latter form more clearly says what it means.
