### ISSUE TITLE
Documentation for cops

### ISSUE THREAD

**Issue by bgeuken** [rubocop-rspec/rubocop-rspec#540]
It seems that there isn't any documentation for the existing cops available. We currently in the process of adding rubocop-rspec to our code base. It would be really helpful to be able to point to some doc when discussing / deciding if and how configured we want to have a certain cop.

**Comment by Darhazer** [comment]
http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec

**Comment by bquorning** [comment]
Does the rubydoc.info documentation provide what you need @bgeuken, or would a documentation site similar to RuboCop’s http://rubocop.readthedocs.io/en/latest be of more use?

Or should we perhaps just link to rubydoc.info in the README? 😳

**Comment by Ana06** [comment]
I personally think that something like http://rubocop.readthedocs.io/en/latest would be better. 

In the meanwhile I would link the Rubydoc in the Readme, as it is currently not that easy to find.

**Comment by bgeuken** [comment]
> bquorning commented 9 minutes ago
> Does the rubydoc.info documentation provide what you need @bgeuken, or would a documentation site similar to RuboCop’s http://rubocop.readthedocs.io/en/latest be of more use?

The rubydoc.info docu already helps a lot. Having something like the RuboCop documentation would of course be awesome.

> Or should we perhaps just link to rubydoc.info in the README?

Yes, please:-)

Thanks for the quick reply

**Comment by Darhazer** [comment]
ReadTheDocs documentation is published at http://rubocop-rspec.readthedocs.io/en/latest/
