### ISSUE TITLE
Repository moved

### ISSUE THREAD

**Issue by bquorning** [rubocop-rspec/rubocop-rspec#569]
Hey all. Please note that we have moved the repository from from https://github.com/backus/rubocop-rspec to https://github.com/rubocop-rspec/rubocop-rspec. According to https://help.github.com/articles/about-repository-transfers/ everything should continue to work as before. 

That article also recommends that you update your local clone:

> However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL. You can do this by using git remote on the command line:
>
> `git remote set-url origin new_url`

**Comment by Darhazer** [comment]
It seems we need to update the gemnasium.com config as well

**Comment by bquorning** [comment]
Gemnasium is [shutting down on May 15](https://gemnasium.com/blog/gemnasium-is-acquired-by-gitlab/) because GitHub now has built-in vulnerability scanning. See https://github.com/rubocop-rspec/rubocop-rspec/network/dependencies.

I think we should just remove the Gemnasium from the readme.
