### ISSUE TITLE
FactoryBot/DynamicAttributeDefinedStatically records an offence when using Ruby's Symbol#to_proc behaviour

### ISSUE THREAD

**Issue by timrogers** [rubocop-rspec/rubocop-rspec#575]
In a FactoryBot factory, you can define "before" and "after" callbacks as follows:

```ruby
FactoryBot.define do
  factory :widget do
    after(:create) { |widget| widget.create_catalogue_entry! }
  end
end
```

The specified callback (a block) is called after `FactoryBot.create`.

[Because of the magic of Ruby's `Symbol#to_proc`](https://www.brianstorti.com/understanding-ruby-idiom-map-with-symbol/), this can also be written as:

```ruby
FactoryBot.define do
  factory :widget do
    after(:create, &:create_catalogue_entry!)
  end
end
```

However, when you do this, you get an offence like the following logged:

```
spec/factories/widget.rb:3:5: C: FactoryBot/DynamicAttributeDefinedStatically: Use a block to set a dynamic value to an attribute. (http://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/FactoryBot/DynamicAttributeDefinedStatically)
    after(:create, &:create_catalogue_entry!)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
```

If you ask Rubocop to autocorrect, you get a result like this, which is not valid Ruby syntax:

```ruby
FactoryBot.define do
  factory :widget do
    after { :create, &:create_catalogue_entry! }
  end
end
```

The cop should be able to see you're using `Symbol#to_proc`, and treat that as equivalent to a normal block, which is "dynamic".

**Comment by Darhazer** [comment]
I believe this was fixed in #562 - published in v 1.24
Can you confirm?

**Comment by timrogers** [comment]
Looks like it. Leave that with me.

**Comment by timrogers** [comment]
You’re right; I was behind a version. Closing.
