### ISSUE TITLE
Cop idea: detect 1.times / 2.times and suggest using once / twice

### ISSUE THREAD

**Issue by Darhazer** [rubocop-rspec/rubocop-rspec#615]
`exactly(1).times` -> `.once`
`exactly(2).times` -> `.twice`
`atLeast(1).times` -> `atLeast(:once)`
`atLeast(2).times` -> `atLeast(:twice)`
`atMost(1).times` -> `atMost(:once)`
`atMost(2).times` -> `atMost(:twice)`

zero is a special case and might fit in another cop:
`receive().exactly(0).times` -> `not_to receive()` (related to #607)

**Comment by bquorning** [comment]
Good idea. But let’s stick to snake_case 😉
